language: node_js

node_js:
  - "6"

sudo: false

addons:
  apt:
    sources:
      - sourceline: "ppa:wine/wine-builds"
    packages:
      - winehq-staging

script:
  - yarn run build

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
